### ISSUE TITLE
Add intellisense for docker compose files

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2539]
Creating this umbrella issue since there are a bunch of different things that basically boil down to creating a language server + intellisense + etc. for compose files.

- [ ] Linting support (Compose schema validation) (https://github.com/microsoft/compose-language-service/issues/84)
- [ ] Volume pathing intellisense (https://github.com/microsoft/compose-language-service/issues/85)
- [ ] Snippets for some well-known services (postgres, redis, etc.), including common ports (https://github.com/microsoft/compose-language-service/issues/86) 
- [ ] Image autocomplete suggestions (https://github.com/microsoft/compose-language-service/issues/87)
- [x] Port snippets (#2535)
- [x] Autocompletions for subsequent parts--e.g., when typing 're', complete to 'restart:', then suggest 'always' and other valid suggestions (#2713)
- [x] Linting support (YAML validation) (#37)
- [x] Volume snippets (#2536)
- [x] URL click behavior for base images (#2200)
- [x] Auto format indentation on save/while typing (#2714)
- [x] Updated icon theme: update https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/vs-seti-icon-theme.json (so all compose files can get pink whale that currently only appears for `docker-compose.yml` and `docker-compose.override.yml`) (https://github.com/microsoft/vscode/commit/554182620f43390075d8c7e7fa36634288ef4e2d) (should be available in VSCode 1.61.0)
- [x] Syntax highlighting
- [x] Language ID for `file.associations` (#206) (https://github.com/microsoft/vscode/pull/118042)
- [x] Defining a language with more specific file names would help with spurious activations. `onLanguage:yaml` accounts for about 60% of all our activations; I'm sure many (or most) of those are not actually docker-compose files

Maybe/currently not possible:
- ~~Semantic highlighting~~ (I can't think of a use case)
- ~~Change the [file picking logic](https://github.com/microsoft/vscode-docker/blob/main/src/utils/quickPickFile.ts) to be better and language-based~~ (I don't think currently possible)
- ~~Port-in-use intellisense~~ (Gross, port scanning)

Other:
- ~~docker-stack.yml (#520)~~

Update: as of 2 Aug 21, about 33% of activations are due to Dockerfiles being opened, now about 25% are due to Docker Compose files being opened, with most of the balance being task runs and the Docker Explorer. This is down from 60% YAML, 30% Dockerfile, 10% others. This is a big improvement; by narrowing to activating for Compose documents only, the activations for Compose/YAML are way lower--this means far less spurious activation.

**Comment by ucheNkadiCode** [comment]
Other Notes & Ideas
Adding a "well known" service to a compose file through a snippet. (Redis, postgres)
Warnings for incorrect indentation levels of a service or attributes (e.g "attribute dockerfile does not exist at this hierarchy)
Warnings for incorrect file paths or files that don't exist in the context of the project - mainly applies to context attribute and volume attribute
Warnings for misspelled sections (if you misspell volumes, ports, environment etc, there are no warnings)

**Comment by thernstig** [comment]
@bwateratmsft should the `docker-stack.yml` be scrapped?

According to https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file and https://docs.docker.com/compose/compose-file/ - the latest specs says a file should be named `compose.yaml` it says:

> The default path for a Compose file is <code>compose.yaml</code> (preferred) or <code>compose.yml</code> in working directory.  Compose implementations SHOULD also support <code>docker-compose.yaml</code> and <code>docker-compose.yml</code> for backward compatibility.

I also noticed now that when I renamed my file to `compose.yaml` it does not get the "red Moby Dick icon" but rather a normal `.yaml` icon.

**Comment by bwateratmsft** [comment]
> @bwateratmsft should the `docker-stack.yml` be scrapped?

Yeah, probably. :smile:

> According to https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file and https://docs.docker.com/compose/compose-file/ - the latest specs says a file should be named `compose.yaml` it says:
> 
> > The default path for a Compose file is `compose.yaml` (preferred) or `compose.yml` in working directory.  Compose implementations SHOULD also support `docker-compose.yaml` and `docker-compose.yml` for backward compatibility.
> 
> I also noticed now that when I renamed my file to `compose.yaml` it does not get the "red Moby Dick icon" but rather a normal `.yaml` icon.

I had not noticed this change, thank you for bringing it to our attention! I'm going to make a separate work item to cover that for the time being.

**Comment by bwateratmsft** [comment]
We will be able to do this incrementally which is good. The minimum viable product would include a language ID being defined, and syntax highlighting to support it. This would have the side benefit of reducing spurious activations for non-compose YAML files.

**Comment by rcjsuen** [comment]
@bwateratmsft Is the plan to implement this with VS Code APIs or as a language server? 🤔

**Comment by bwateratmsft** [comment]
Most likely a language server since I assume a lot of these features would require that.

**Comment by bwateratmsft** [comment]
Might get a language ID from VSCode itself: https://github.com/microsoft/vscode/pull/118042

**Comment by bwateratmsft** [comment]
The VSCode team has merged that [change](https://github.com/microsoft/vscode/pull/118042), so now there is a compose language ID of `dockercompose`. It matches the following patterns:
```json
"filenamePatterns": [
    "compose.yml",
    "compose.yaml",
    "compose.*.yml",
    "compose.*.yaml",
    "*docker*compose*.yml",
    "*docker*compose*.yaml"
],
```

I'll start making some changes in the Docker extension to best support this. Thanks @alexr00! This is a big win for us!

**Comment by bwateratmsft** [comment]
Moved to 1.17 per discussion in team meeting, and we'll make this high pri for 1.17.

**Comment by bwateratmsft** [comment]
Icon theme gets defined here: https://github.com/jesseweed/seti-ui/blob/24bb6afe6f9c136fb660d39ed8d46956cb94eb13/styles/components/icons/mapping.less#L542-L551

It looks like putting that change in the theme might not be the right place for it--it only marks a few very specific Dockerfile/compose file names. Instead, we should consider using https://github.com/microsoft/vscode/issues/14662#issuecomment-787912133.

**Comment by bwateratmsft** [comment]
The pink whale icon has been extended to all `dockercompose` documents via https://github.com/microsoft/vscode/commit/554182620f43390075d8c7e7fa36634288ef4e2d.

**Comment by bwateratmsft** [comment]
Rather than continually moving this a milestone at a time, I'm going to make sure issues exist for each of the remaining tasks in https://github.com/microsoft/compose-language-service, and close this one.

**Comment by thernstig** [comment]
@bwateratmsft the original post in this thread already contains existing issues. Just open them up again?

**Comment by bwateratmsft** [comment]
Yeah, that's a better idea. I'll do that and transfer them to the other repo.
