### ISSUE TITLE
Modernize our webpacking, linting, testing, etc.

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2606]
Our webpacking strategy is getting dated and needs some TLC. Creating a new VSCode extension now (with `yo code`) results in a very different extension, with webpacking already set up, along with much more. This would allow us to modernize a lot of things and would be preferable to what we're doing now.

Checklist:
- [x] Use recommended linter settings instead of having a long list of rules and exceptions (#2836)
- [x] Use newer webpack loaders and plugins (#2883)
- [x] Use the newer `webpack watch` capabilities, alter tests to support this (#3078)
- [x] GitHub Actions for build (#3097)
- [x] ~~Split up webpack chunks to~~ optimize code loading time to the max (#3103)

**Comment by bwateratmsft** [comment]
We should consider dumping Gulp as part of this. It hasn't been updated in years and results in a lot of Dependabot alerts.

**Comment by bwateratmsft** [comment]
@karolz-ms @philliphoff the current state we're at is webpacking is linting is fixed and webpacking is modernified. The primary remaining work is to switch to `webpack --watch` for the dev loop. This is absolutely not urgent so it can wait.

I have some provisional changes to accomplish that in the [bmw/modernize](https://github.com/microsoft/vscode-docker/tree/bmw/modernize) branch; I wouldn't necessarily consider this work complete--it needs a bit more work--but it's getting there.

What I know is still needed in that branch:

- Make sure tests are running and successful--and also, make sure a failing test fails the build
- Update the AZDO yaml pipelines to use the new NPM scripts
- Probably branch off the GitHub Action this branch adds into a different PR
