### ISSUE TITLE
Support third-party registries

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-docker#869]
Specifically requested (but goal is generic support), in no particular order:

Open:
- [ ] goharbor.io (see #878, #3449, #3965)
- [ ] ECR (Amazon, see #3202, #3604)
- [ ] GCR (Google) (+3 see #394, #2890)
- [ ] quay.io (+4 see #390)
- [ ] DTR (Enterprise Docker trusted registry) (see #3325)
- [ ] Cloudsmith (see #1887)
- [ ] Aliyun (see #1964)
- [ ] Portus (see #2735)
- [ ] Digital Ocean (see #2879)
- [ ] Generic registries with self-signed certificate (#3639)
- [ ] Artifactory (#4011)

**Blocked** on no/partial Registry V2 support:
- [ ] V2 registries that don't use `/v2/` endpoint (see #3562)
- [ ] GitHub (see #1525, #1938, #3686)
- [ ] GitLab self-hosted (+6 see #1832, #2457, #2735, #3119, #3271, #3813)
- [ ] `harbor.korporate.org` (see #1927)
- [ ] GitLab Groups (see #1970)
- [ ] IBM Container Registry (see #3961)

Done:
- [x] DockerHub
- [x] Azure
- [x] GitLab (+25-ish see #162)
- [x] Generic V2 registry (+2)

**Comment by gauravlakhani** [comment]
while connecting using private registry option, is private Docker DTR (Enterprise Docker trusted registry) supported at all?

**Comment by StephenWeatherford** [comment]
@gauravlakhani Support for registries beyond Docker Hub is fairly new, we haven't tested on DTR. I've added it to the list.

**Comment by shaneholloman** [comment]
@here champion!

**Comment by imkhairulikhwan** [comment]
Hi, do we have an estimated date for this to complete?

**Comment by Nhimself** [comment]
Following this...

**Comment by bwateratmsft** [comment]
@BigMorty I think that we should take this one for 0.12.0...

**Comment by BigMorty** [comment]
Agree we should try to get it into .12 or .14 (we are skipping .23 😉)

**Comment by bwateratmsft** [comment]
This could potentially require and/or take advantage of https://github.com/microsoft/vscode/issues/88309

**Comment by bwateratmsft** [comment]
I've spent a lot of time researching in the past few days. Unfortunately this is going to be extremely difficult, due to two main issues:

1. **No / incomplete [Registry V2 API](https://docs.docker.com/registry/spec/api/) support**
    - GitHub, Docker Hub lack the `_catalog` endpoint
    - GitLab has no V2 API support at all, but instead a custom API
    - ECR has their own API, but supposedly supports the V2 API
    - DTR has no V2 API; or at least I can't find any docs suggesting it does
1. **OAuth flows totally inconsistent with each other and with the [spec](https://docs.docker.com/registry/spec/auth/oauth/)**
    - Azure and Quay require a web page sign-in
    - Docker Hub has a hilariously broken auth flow--it issues tokens regardless of anything (though the tokens will not work), and does not issue refresh tokens even when asked for them, and does not accept `POST`'s for OAuth tokens like the spec says
    - GCR and ECR use credential helpers--not something we can use
    - Quay requires the users to create a client application, and provide its ID to any clients (e.g. this extension). Possible, but onerously difficult.
    - goharbor.io might be the only one with a proper implementation that also permits password auth? At least, their docs sound like it.

Implementing support for each registry with their own custom APIs is a non-starter. Dealing with the OAuth flows is possible, but guaranteed to result in a lot of bad user experiences, due to the complexity and prerequisite setup that most of them demand.

**Comment by kautkata** [comment]
I stumbled upon this in our company. Our setup is basic docker registry instance as container via image `registry:2` image id `708bc6af7e5e` while Oauth2  authentication is handled by second container via `cesanta/docker_auth:latest` image id `dd1aae63f028` with some kind of OpenLdap in background.

Most of tools which I have used can handle this combination well as it implements basic Oauth2 flow without redirects to web UI or other magical stuff. For us standard Oauth2 support would be enough.

**Comment by bwateratmsft** [comment]
@kautkata I'd love to learn more about your setup and see if we can get support added. `registry:2` OAuth is a starting point that would help a lot of folks.

Do you have any setup guides on what you have? When doing `docker login` from the command line, what do you use for username/password? I've seen options of actual password, PAT, OAuth token, and more...

**Comment by kautkata** [comment]
@bwateratmsft Here you go.

Registry and auth endpoint configuration files are modified (you know I'm not supposed to expose our internal details and stuff) but in general they still should work. TLS certificates are pretty basic, they where generated via openssl command line tools.

From docker container perspective it looks like this:
[dockerps.txt](https://github.com/microsoft/vscode-docker/files/4291244/dockerps.txt)

Registry container gets started via: `/usr/bin/docker run --name registry --mount type=bind,source=/etc/docker-registry,destination=/cfg,readonly --mount type=bind,source=/mnt1/docker/registry,destination=/var/lib/registry -p 443:443 registry:2 /cfg/config-registry.yml`

Auth endpoint gets started via: `/usr/bin/docker run --name registry-auth --mount type=bind,source=/etc/docker-registry,destination=/cfg,readonly -p 442:442 cesanta/docker_auth:latest -logtostderr /cfg/config-auth.yml`

Registry configuration file: [config-registry.yml](https://github.com/microsoft/vscode-docker/files/4291252/config-registry.txt)

Auth endpoints configuration file: [config-auth.yml](https://github.com/microsoft/vscode-docker/files/4291258/config-auth.txt)

On server `/etc/docker-registry` directory contains following files: `config-auth.yml config-registry.yml ldap_password server-cert.pem server-key.pem`

From ldap users perspective using docker daemon running on Linux it works as a charm via:
```
docker login -u <ldap username> docker.internaldomain.lv
Password:
WARNING! Your password will be stored unencrypted in /home/<os user>/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```
Afterwards specified OpenLDAP user can push images to registry, example: `docker.internaldomain.lv/user/<ldap user name>/test:latest`

**Comment by bwateratmsft** [comment]
This is great info, thanks a ton @kautkata. I'll be spending some time in the 1.1 release looking into this to see what we can do.

**Comment by fathom-matthew** [comment]
+1, GCR support would be very nice to have

**Comment by bwateratmsft** [comment]
@fathom-matthew @Nhimself @imkhairulikhwan (I @'d you all since you have commented recently :smile:):

GCR, ECR, and Quay all require some extra setup (each needs work done in their respective portals; GCR and ECR also require installing their respective command-line utilities). What do you guys think would be the best user experience to enable these registries but still set users up for success by getting them through the necessary setup?

**Comment by bwateratmsft** [comment]
Linking to #2033 so those subscribed to this issue can see that.

**Comment by karolz-ms** [comment]
@bwateratmsft how does the [new GitHub registry](https://github.blog/2020-09-01-introducing-github-container-registry/) fit into the picture? 

I was looking for some details esp. around RegistryV2 support, but from what [GitHub has on their website](https://docs.github.com/en/packages/getting-started-with-github-container-registry) I can't really say if full V2 protocol is supported...

**Comment by bwateratmsft** [comment]
Pretty sure the "new" GitHub registry is just the existing GitHub registry but "relaunched" to draw more attention. It's V2 compliant minus the `_catalog` endpoint. In the new [extensibility model](https://github.com/microsoft/vscode-docker/issues/2033) I'm making such monolith registries possible to connect to but it will require adding each repository manually since there's no way to list repositories.

**Comment by ZeeMoros** [comment]
+1 for Gitlab self-hosted

**Comment by JustinGrote** [comment]
@bwateratmsft Any update on GCR? They have a bit more documentation and are at least Docker CLI compatible.
https://docs.github.com/en/free-pro-team@latest/packages/guides/connecting-a-repository-to-a-container-image

**Comment by bwateratmsft** [comment]
@JustinGrote We had been underway on a more generic and extensible registry provider model but it got shelved. I'm not sure what priorities will be coming up this year so I can't say what to expect.

**Comment by aarontcannon** [comment]
+1 for gitlab self-hosted registries

**Comment by vivekrp** [comment]
Any update for the ECR and GCR?

**Comment by bwateratmsft** [comment]
> Any update for the ECR and GCR?

@vivekrp We're working on a proposal for registry extensibility that would make it simple to add providers: #2033

We'd definitely be interested in your feedback on it!

**Comment by quicktrick** [comment]
+1 for Gitlab self-hosted

**Comment by julian-poidevin** [comment]
+1 for Gitlab self-hosted

**Comment by elasticdotventures** [comment]
+1 Github Container Registry,

the github contact @Phanatic in #1525 seems to have moved on with no response, the thread locked (only for contributors)

I've posted requesting an update here (is there a github issue for this?)
https://github.community/t/ghcr-io-docker-http-api/130121/2

**Comment by Aleksei-Badyaev** [comment]
I would like to add that the docker image registry built into Gitea: [Gitea Container Registry](https://docs.gitea.io/en-us/packages/container/) also does not contain endpoint /v2/.

**Comment by KevinPoole** [comment]
+1 for Gitlab self-hosted

**Comment by yaroslavsadin** [comment]
+1 for Gitlab self-hosted

**Comment by dantebarba** [comment]
+1 Gitlab self-hosted

**Comment by laurie-kepford** [comment]
following

**Comment by wdennis** [comment]
+1 for goharbor.io

Latest vscode (1.73.1) it seems to connect, but gives error when selected:
`Error: Unexpected token < in JSON at position 0`

**Comment by MetallianFR68** [comment]
+1 for Gitlab self-hosted

**Comment by alexfricker** [comment]
+1 for Gitlab self-hosted.

self hosted uses v2 and `_catalog` endpoint; I'm curious what the issue is since that seemed to be the blocker originially?

**Comment by Mk-arc** [comment]
+1 for Gitlab self-hosted.

**Comment by OperativeThunny** [comment]
+1 for Gitlab self-hosted for me as well. My environment is very constrained so I tried setting up a personal access token in the gitlab self hosted instance, but there is no way using the generic docker option or the gitlab option to connect (tried editing hosts file to point gitlab.com to self hosted instance, but that did not work the url it attempted was a 404)

**Comment by mjgardner** [comment]
@bwateratmsft [wrote](https://github.com/microsoft/vscode-docker/issues/869#issuecomment-592066589):
> 1. **No / incomplete [Registry V2 API](https://docs.docker.com/registry/spec/api/) support**
>    
>    * GitLab has no V2 API support at all, but instead a custom API

Then @alexfricker [wrote](https://github.com/microsoft/vscode-docker/issues/869#issuecomment-1537183954):
> it does look like self hosted uses v2 and `_catalog` endpoint fwiw

GitLab’s Container Registry API documentation [lists instance-wide Docker V2 API endpoints](https://docs.gitlab.com/ee/api/container_registry.html#instance-wide-endpoints) apart from their custom API. It looks like one just uses HTTP Basic Auth with the username and password (or [Personal Access Token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) if using 2FA) as part of [the first request for a Bearer token](https://docs.gitlab.com/ee/api/container_registry.html#obtain-token-from-gitlab).

**Comment by Hyperclaw79** [comment]
Is the Github integration completed? I am able to add the Registry and push to it but I'm seeing an error message when trying to list the packages.
<img width="275" alt="image" src="https://github.com/microsoft/vscode-docker/assets/29298411/5b8b2eb6-1709-4850-ad4b-a7c0c35d412a">

This is the complete error message:\
`Error: Request with GET/HEAD method cannot have body`

Is this related to the discussion regarding GHCR now having `_catalog` or am I missing something?

**Comment by bwateratmsft** [comment]
GitHub Container Registry is not yet supported but we are actively working on a significant revamp of the registries functionality, and have included support of GitHub in that work.

**Comment by bwateratmsft** [comment]
That wasn't in the plan but you could create a new issue to suggest that.

**Comment by LordMilutin** [comment]
I don't know what you did but private registries are no longer visible for connection...
There is no way anymore to connect them. Please bring back this functionality as this was my only way to manage the registry with a nice UI...
